### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by Yolwoocle** [WetDesertRock/GifCat#7]
Well, obviously not, since the last commit is from 5 years ago, but are there still plans to update it? It currently doesn't work in the latest versions of LÖVE.

**Comment by WetDesertRock** [comment]
I currently have no plans. I should probably archive this project to make that clear. However feel free to fork it and update it. It likely won't require too much more than maybe updating the lua headers and maybe slight binding adjustments. Although to be fair I'm not sure why it is broken.

**Comment by WetDesertRock** [comment]
Actually, see the PR in here: https://github.com/WetDesertRock/GifCat/pull/6

If you are able to verify it works for me I'll merge it.

**Comment by Yolwoocle** [comment]
I can confirm that it works:  
![1646295083](https://user-images.githubusercontent.com/54135715/156523754-fa5911ad-3b1e-4a87-a67f-847e37096b86.gif)
Note that I didn't do extensive tests, but most essential features are working.  
I also made a pull request updating the README, since some headers were broken: #8 
By the way, thank you for making this module, it was like a godsend.

**Comment by WetDesertRock** [comment]
Thanks for your help! I've merge it all in!

Glad it is helping you out, your game looks pretty nice by the way!
